commit at 18:18:19

diff --git a/.github/workflows/only-change-own-files.yml b/.github/workflows/only-change-own-files.yml
--- a/.github/workflows/only-change-own-files.yml
+++ b/.github/workflows/only-change-own-files.yml
@@ -91,32 +91,32 @@ jobs:
     - name: "validation"
       continue-on-error: true
       run: |
-          echo "${{ steps.diffs.outputs.files_ok }}"
-          MATCHING=$(echo "${{ steps.diffs.outputs.files_ok }}" | tr ' ' '\n' | grep "[bm]\d-[a-z]\w*" || "")
-          NONMATCHING=$(echo "${{ steps.diffs.outputs.files_ok }}" | tr ' ' '\n' | grep -v "[bm]\d-[a-z]\w*" || "")
+          which tr
+          MATCHING=$(echo "${{ steps.diffs.outputs.files_ok }}"  | grep "[bm]\d-[a-z]\w*" || echo "")
+          NONMATCHING=$(echo "${{ steps.diffs.outputs.files_ok }}" | tr ' ' '\n' | grep -v "[bm]\d-[a-z]\w*" || echo "")
           echo "MATCHING: $MATCHING "
           echo "NONMATCHING: $NONMATCHING "
           echo "-----"
-          if [ "" -neq "$NONMATCHING" ]; then
-             echo " includes invalid paths!"
-             echo "NONMATCHING: $NONMATCHING "
-          else
+          if [ -z "$NONMATCHING" ]; then
              echo " all paths ok."
+          else
+             echo " includes invalid paths!"
+             echo "NONMATCHING: $NONMATCHING " 
           fi
    
         
     - name: "report error"
       run: |
-       echo "ok: ${{ steps.diffs.outputs.files_ok }}"
-       echo "nok: ${{ steps.diffs.outputs.files_not_ok }}"
-       if [[ "" != ${{ steps.diffs.outputs.files_not_ok }} ]]; then 
-                echo "ERROR: More files changed than allowed!"
+        echo "ok: ${{ steps.diffs.outputs.files_ok }}" | tr ' ' '\n'
+        echo "nok: ${{ steps.diffs.outputs.files_not_ok }}" | tr ' ' '\n'
+        if [ -z ${{ steps.diffs.outputs.files_not_ok }} ]; then 
+          echo "all good"       
+        else
+           echo "ERROR: More files changed than allowed!"
                 echo "------ Additional Files: "
-                echo ${{ steps.diffs.outputs.files_not_ok }}
+                echo ${{ steps.diffs.outputs.files_not_ok }} | tr ' ' '\n'
                 echo "------ Allowed Files:"
-                echo ${{ steps.diffs.outputs.files_ok }}
-                exit 123
-            else
-                echo "all good"
+                echo ${{ steps.diffs.outputs.files_ok }} | tr ' ' '\n'
+                exit 123    
          fi
 
