commit at 21:37:23

diff --git a/.github/workflows/only_project_files.yml b/.github/workflows/only_project_files.yml
--- a/.github/workflows/only_project_files.yml
+++ b/.github/workflows/only_project_files.yml
@@ -1,57 +1,57 @@
 on:
-    pull_request:
-      branches:
-        - test_gh_pr_actions
-        - main
-        - schedule
-  
-  jobs:
-    check_files_in_pr:
-      runs-on: ubuntu-latest
-      # Required permissions
-      permissions:
-        pull-requests: read
-      steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: false
-          fetch-depth: 20
-  
-      - name: extract project id
-        continue-on-error: true
-        id: extract_pid
-        env: 
-          PR_TITLE: ${{ github.event.pull_request.title }}
-        run: |
-            project_id=$(bin/extract_pid_from_pr_title.sh $PR_TITLE)
-            pid_ok=$?
-            echo "project_id=$project_id" >> $GITHUB_OUTPUT
-            exit $pid_ok 
-  
-      - name: 'changed files'
-        uses: dorny/paths-filter@v3
-        id: filter
-        with:
-          list-files: 'shell'
-          filters: | 
-            in_project:
-              - 'content/**/${{ steps.extract_pid.outputs.project_id }}-*/**'
-            other_files:
-              - '!content/**/${{ steps.extract_pid.outputs.project_id }}-*/**'
-  
-      - name: files in project folder
-        if: steps.filter.outputs.in_project == 'true'
-        run: |
-          echo "--------- project_files:"
-          echo ${{ steps.filter.outputs.in_project_files }} | tr ' ' '\n'
-          
-      
-      - name: 'found changed files outside of project folder!!'
-        if: steps.filter.outputs.other_files == 'true'
-        run: |
-          echo "--------- non_project_files (may not be part of project update PR!):"
-          echo ${{ steps.filter.outputs.other_files_files }} | tr ' ' '\n'
-          echo "ERROR: found files outside of project folder"
-          exit 321
+  pull_request:
+    branches:
+      - test_gh_pr_actions
+      - main
+      - schedule
+
+jobs:
+  check_files_in_pr:
+    runs-on: ubuntu-latest
+    # Required permissions
+    permissions:
+      pull-requests: read
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        submodules: false
+        fetch-depth: 20
+
+    - name: extract project id
+      continue-on-error: true
+      id: extract_pid
+      env: 
+        PR_TITLE: ${{ github.event.pull_request.title }}
+      run: |
+          project_id=$(bin/extract_pid_from_pr_title.sh $PR_TITLE)
+          pid_ok=$?
+          echo "project_id=$project_id" >> $GITHUB_OUTPUT
+          exit $pid_ok 
+
+    - name: 'changed files'
+      uses: dorny/paths-filter@v3
+      id: filter
+      with:
+        list-files: 'shell'
+        filters: | 
+          in_project:
+            - 'content/**/${{ steps.extract_pid.outputs.project_id }}-*/**'
+          other_files:
+            - '!content/**/${{ steps.extract_pid.outputs.project_id }}-*/**'
+
+    - name: files in project folder
+      if: steps.filter.outputs.in_project == 'true'
+      run: |
+        echo "--------- project_files:"
+        echo ${{ steps.filter.outputs.in_project_files }} | tr ' ' '\n'
+        
+    
+    - name: 'found changed files outside of project folder!!'
+      if: steps.filter.outputs.other_files == 'true'
+      run: |
+        echo "--------- non_project_files (may not be part of project update PR!):"
+        echo ${{ steps.filter.outputs.other_files_files }} | tr ' ' '\n'
+        echo "ERROR: found files outside of project folder"
+        exit 321
   
   
